import type { Integration, IntegrationTab } from '../models/integration.model';

export const INTEGRATION_STATION_BREADCRUMB_BASE = 'Workspace';
export const INTEGRATION_STATION_BREADCRUMB_ACTIVE = 'Integration Station';
export const INTEGRATION_PAGE_TITLE = 'Connect Your Tools';
export const INTEGRATION_PAGE_SUBTITLE =
  'Supercharge your workflow by syncing data across your favorite platforms.';
export const INTEGRATION_SEARCH_PLACEHOLDER = 'Search integrations...';

export const INTEGRATION_TABS: IntegrationTab[] = [
  { id: 'all', label: 'All Integrations' },
  { id: 'crm', label: 'CRM' },
  { id: 'communication', label: 'Communication' },
  { id: 'data', label: 'Data & Enrichment' },
  { id: 'calendar', label: 'Calendar' },
  { id: 'storage', label: 'Storage' },
];

export const INTEGRATIONS_LIST: Integration[] = [
  {
    id: 'hubspot',
    name: 'HubSpot',
    icon: 'logos:hubspot',
    category: 'crm',
    status: 'connected',
    description: 'Sync contacts and deals automatically.',
    actionType: 'manage',
    actionLabel: 'Manage',
    lastSync: '2 mins ago',
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    icon: 'logos:salesforce',
    category: 'crm',
    status: 'disconnected',
    description: 'Import opportunities and account data.',
    actionType: 'connect',
    actionLabel: 'Connect',
  },
  {
    id: 'pipedrive',
    name: 'Pipedrive',
    icon: 'logos:pipedrive',
    category: 'crm',
    status: 'connected',
    description: 'Keep sales pipelines in perfect sync.',
    actionType: 'manage',
    actionLabel: 'Manage',
  },
  {
    id: 'gmail',
    name: 'Gmail',
    icon: 'logos:google-gmail',
    category: 'communication',
    status: 'active',
    description: 'Sync emails to track replies & opens.',
    actionType: 'manage',
    actionLabel: 'Manage',
    showToggle: true,
    toggleChecked: true,
    badgeStyle: 'active',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn Sales Nav',
    icon: 'logos:linkedin-icon',
    category: 'communication',
    status: 'disconnected',
    description: 'Directly import saved leads to lists.',
    actionType: 'connect',
    actionLabel: 'Connect',
  },
  {
    id: 'slack',
    name: 'Slack',
    icon: 'logos:slack-icon',
    category: 'communication',
    status: 'connected',
    description: 'Send campaign notifications to #sales.',
    actionType: 'configure',
    actionLabel: 'Configure Webhooks',
  },
  {
    id: 'clearbit',
    name: 'Clearbit',
    icon: 'simple-icons:clearbit',
    iconColor: '#3b82f6',
    category: 'data',
    status: 'connected',
    description: 'Enrich lead data automatically.',
    actionType: 'api',
    actionLabel: 'Manage',
    apiMasked: true,
  },
  {
    id: 'apollo',
    name: 'Apollo.io',
    icon: 'apollo',
    iconPlaceholder: 'A',
    category: 'data',
    status: 'error',
    description: 'Additional lead source database.',
    actionType: 'reconnect',
    actionLabel: 'Reconnect',
    badgeStyle: 'error',
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    icon: 'logos:google-calendar',
    category: 'calendar',
    status: 'connected',
    description: 'Sync meetings and schedule follow-ups.',
    actionType: 'manage',
    actionLabel: 'Manage',
  },
  {
    id: 'calendly',
    name: 'Calendly',
    icon: 'logos:calendly',
    category: 'calendar',
    status: 'disconnected',
    description: 'Embed booking links in generated emails.',
    actionType: 'connect',
    actionLabel: 'Connect',
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    icon: 'logos:google-drive',
    category: 'storage',
    status: 'connected',
    description: 'Save generated assets directly to Drive.',
    actionType: 'manage',
    actionLabel: 'Manage',
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    icon: 'logos:dropbox',
    category: 'storage',
    status: 'disconnected',
    description: 'Access and store files in your Dropbox.',
    actionType: 'connect',
    actionLabel: 'Connect',
  },
];
